version: 2
title: "Network Level Analysis"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/source/conf.py

search:
  ignore:
    - '*_exported.py'
    - '*/*_exported.py'


formats:
  - pdf