
[tool.codespell]
# Ref: https://github.com/codespell-project/codespell#using-a-config-file
skip = '.git*'
check-hidden = true
ignore-regex = '\b(Brain Mapp|Reson Med|FPR|Hendler)'
# ignore-words-list = ''
