function inputs = genBaseInputs()
    %GENBASEINPUTS Generate struct of required network-level inputs with
    %   default values
    inputs = struct(...
        'no_permutations', true,...
        'full_connectome', true,...
        'within_network_pair', true,...
        'prob_plot_method',nla.gfx.ProbPlotMethod.DEFAULT,...
        'ranking_method', "Eggebrecht",...
        'edge_chord_plot_method', nla.gfx.EdgeChordPlotMethod.PROB,...
        'fdr_correction', nla.net.mcc.Bonferroni(),...
        'd_thresh_chord_plot', true...
    );
end