function inputs = genBaseInputs()
    %GENBASEINPUTS Generate struct of required network-level inputs with
    %   default values
    inputs = struct(...
        'nonpermuted', true,...
        'full_conn', true,...
        'within_net_pair', true,...
        'prob_plot_method',nla.gfx.ProbPlotMethod.DEFAULT,...
        'ranking_method', nla.RankingMethod.P_VALUE,...
        'edge_chord_plot_method', nla.gfx.EdgeChordPlotMethod.PROB,...
        'fdr_correction', nla.net.mcc.Bonferroni(),...
        'd_thresh_chord_plot', true...
    );
end

