function scaleSelector(src, bounds, plot_figure, parameters, chord_type, callback_function)
    original_figure = src.Parent.Parent;
    modal = figure('WindowStyle', 'normal', 'Units', 'pixels', 'Position',...
        [original_figure.Position(1), original_figure.Position(2), original_figure.Position(3) / 3, original_figure.Position(4) / 3]);
    
    upper_limit_box = uicontrol('Style', 'edit', "Units", "pixels", 'Position', [90, 130, 100, 30], "String",...
        bounds(2));
    upper_limit_box.Position(4) = upper_limit_box.FontSize * 2;
    lower_limit_box = uicontrol('Style', 'edit', "Units", "pixels", 'Position', [90, 100, 100, 30], "String",...
        bounds(1)); 
    lower_limit_box.Position(4) = lower_limit_box.FontSize * 2;

    uicontrol('Style', 'text', 'String', 'Upper Limit', "Units", "pixels", 'Position',...
        [upper_limit_box.Position(1) - 80, upper_limit_box.Position(2) - 2, 80, upper_limit_box.Position(4)]);
    uicontrol('Style', 'text', 'String', 'Lower Limit', "Units", "pixels", 'Position',...
        [lower_limit_box.Position(1) - 80, lower_limit_box.Position(2) - 2, 80, lower_limit_box.Position(4)]);

    apply_button_position = [10, 10, 100, 30];
    apply_button = uicontrol('String', 'Apply',...
        "Callback", {callback_function, upper_limit_box, lower_limit_box, false, plot_figure, parameters, chord_type},...
        "Units", "pixels",...
        'Position', apply_button_position);
    
    close_button_position = [apply_button.Position(1) + apply_button.Position(3) + 10,...
        apply_button.Position(2), apply_button.Position(3), apply_button.Position(4)];
    uicontrol('String', 'Close', 'Callback', @(~, ~)close(modal), "Units", "pixels", 'Position',...
        close_button_position);
end