name: export-mlapp-files
run-name: Exporting .mlapp files to .m files
on: [push]
env:
  MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }}
jobs:
  export-mlapp-files:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run python extract script
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Export mlapp files
        run: python export_mlapp.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git commit -m "Add Changes" -a
      - name: Push Changes
        run: git push