name: Run Matlab Tests
on: [push]
env:
  MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }}
jobs:
  matlab-test-job:
    name: Run Matlab tests and generate reports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2021a
          cache: true
          products: >
            MATLAB
            Bioinformatics_Toolbox
            Parallel_Computing_Toolbox
            Statistics_and_Machine_Learning_Toolbox
            Image_Processing_Toolbox
      - name: Check Matlab Install
        uses: matlab-actions/run-command@v2
        with:
          command: ver
      # - name: Run script
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: addpath(genpath(pwd)); results = runTests(); assertSuccess(results)
      #     use-parallel: true
      - name: Run Tests
        uses: matlab-actions/run-tests@v2
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          use-parallel: true
          select-by-folder: +nla/unittests; +nla/+edge/unittests; +nla/+gfx/unittest; +nla/+net/unittests